sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

env:
  - LPN_COMMAND=checkContainer
  - LPN_COMMAND=checkImage
  - LPN_COMMAND=deploy
  - LPN_COMMAND=license
  - LPN_COMMAND=pull
  - LPN_COMMAND=rm
  - LPN_COMMAND=rmi
  - LPN_COMMAND=run
  - LPN_COMMAND=start
  - LPN_COMMAND=stop
  - LPN_COMMAND=tags
  - LPN_COMMAND=version

before_install:
  - |
    sudo apt update -y
    sudo apt install realpath -y
    go get gotest.tools/gotestsum
    gem update --system 3.0.8
    gem install bundler
    bundle install

install:
  - |
    if [ "$LPN_COMMAND" != "license" ] && [ "$LPN_COMMAND" != "tags" ] && [ "$LPN_COMMAND" != "version" ]; then
      ./scripts/pull-images.sh
    fi
  - go build -o ./bin/lpn

script:
  - |
    cucumber features/$LPN_COMMAND.feature