name: End-To-End tests

on:
  push:
    branches:    
      - develop
      - master
  pull_request:
    branches:
      - master
      - develop

env:
  GO111MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [checkc, checki, deploy, license, pull, rm, rmi, run, start, stop, tags, version]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          ./.github/scripts/install-dependencies.sh
          go get -v -t -d ./...
          if [ "${{ matrix.command }}" != "license" ] && [ "${{ matrix.command }}" != "tags" ] && [ "${{ matrix.command }}" != "version" ]; then
            ./.github/scripts/pull-images.sh
          fi

      - name: Build
        run: go build -o ./bin/lpn

      - name: Run E2E tests
        run: cucumber features/${{ matrix.command }}.feature
